### ISSUE TITLE
VideoHeartBeat AdStart event also fire adStart event on Omniture

### ISSUE THREAD

**Issue by LorepRocks** [Adobe-Marketing-Cloud/media-sdks#32]
Hi Everyone, I have a problem I use videoHeartbeat and Omniture, but I realized that when the mediaHeartBeat.event.adStart is fired this same event is fired also on Omniture again, so I was reviewing and I see that when the event aa_ad_start is fired the event towards Omniture is fired too, I found this implementation guide and I found that the event aa_ad_start indicate that: _call be	
sent	to the analytics server._ (https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/nielsen/test_1_standard_playback_video_valid_guide.pdf  Page 10) Could this be the cause of the event being sent to Omniture since the Omniture tracking server is the same one that I have configured in s: sc: tracking_server for the heartbeat?

**Comment by praveek** [comment]
For content starts and ad starts, we also send a ping to adobe analytics(omniture). The aa_ad_start and aa_start heartbeat pings are acknowledgement that the pings have been sent adobe analytics.

Does this answer your question ?

Thanks,
Praveen

**Comment by LorepRocks** [comment]
Thanks for your answer,

Can this ping be registered as an extra event26 from Omniture?

**Comment by praveek** [comment]
The media tracked with these analytics and heartbeat pings populate the predefined media reports in the analytics dashboard. Can you elaborate on the extra event26 ?

**Comment by LorepRocks** [comment]
actually this looks more like a milestone legacy since all these calls that look like extra events have the variable PEV3

**Comment by LorepRocks** [comment]
Maybe do you know how we can deactivate this legacy milestones pev3?

**Comment by praveek** [comment]
Do you have MediaModule related code in AppMeasurement.js ?
Can you reach out to [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html ) and provide additional details on this with network logs ?

**Comment by praveek** [comment]
@LorepRocks Any updates on this issue ?

**Comment by LorepRocks** [comment]
Sorry for the delay in answer, we already solve this issue, thanks for your help!
