### ISSUE TITLE
js sdk VisitorAPI exposed to window

### ISSUE THREAD

**Issue by huozhi** [Adobe-Marketing-Cloud/media-sdks#36]
Inside https://github.com/Adobe-Marketing-Cloud/media-sdks/blob/master/sdks/js/samples/BasicPlayerSample/script/lib/VisitorAPI.js 

```js
       var t = window.Visitor
              , a = t.Ia
              , m = t.Ga;
            a || (a = A);
            m || (m = B);
```

it called itself from window. but actually it won't expose to window explicitly. inside a module, function cannot be hooked on window automatically. it may cause some problem when packaging it with webpack or other tools. would it be possible to add `window.Visitor = ...` in the script?

.

**Comment by praveek** [comment]
Hi @huozhi  

VisitorAPI library is maintained separately from VideoHeartbeat library.  The latest version of the VisitorAPI library can be downloaded by your org admin from "Adobe Analytics" dashboard (Code Manager menu). The latest versions should properly support loading it as module. 

Thanks,
Praveen
