### ISSUE TITLE
Roku Tracking event "Stall" when ad pod plays.

### ISSUE THREAD

**Issue by AleksandrSam** [Adobe-Marketing-Cloud/media-sdks#37]
In Roku platform we have issue.

When Ad Pod plays in changing Ad can triggered Still event (when 1st ad complete and next don't started).
Problem in the adbmobile.brs
In the line:   2222         `if NOT _adb_mediacontext().isInAd()`
You need check AdPod playing or not.
Coulde you update this line to:  `          if NOT _adb_mediacontext().isInAd() and _adb_mediacontext().getAdBreakInfo() = invalid`

**Comment by praveek** [comment]
Hi @AleksandrSam 

We are working on some enhancements to properly track large gaps between ads in adbreak with our next release. 
Until then to handle such cases and avoid going to stall state, i would suggest calling `mediaTrackPause()` at the end of an ad and calling `mediaTrackPlay()` when the next ad started playing. You should also remember to call `mediaTrackPlay()` once the adbreak has completed and the main content resumes playing. 

Thanks,
Praveen
