### ISSUE TITLE
adbmobile.brs has wist linting issues

### ISSUE THREAD

**Issue by vbasky** [Adobe-Marketing-Cloud/media-sdks#38]
Our application has the 

   `"no-private-func": [
      "error"
    ]`

Rule enabled in the `.wistrc.json` which is causing heaps of linting issues when including the ADBMobile.brs into a Scenegraph application. Is there a version of this code that doesn't use private functions

I am not sure if Roku might deprecate using private functions going forward.

**Comment by praveek** [comment]
@vbasky I would suggest modifying your build scripts from linting third party libraries. Calling our public APIs should not cause linting issues in your app code. 

Identifiers in Roku are allowed to start with underscore and have not seen the documentation mention about deprecating it. 

Thanks
Praveen
