### ISSUE TITLE
Roku -  [media/networkService] issue

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/media-sdks#40]
Hi,
i get the below error very randomly every now and then. Can you please let me know what might cause this.

```
BRIGHTSCRIPT: ERROR: roUrlTransfer.SetUrl: Asynchronous operation in progress: pkg:/components/cpc/metrics/vendor/adbmobile.brs(1221)
BRIGHTSCRIPT: ERROR: roUrlTransfer.AsyncGetToString: Asynchronous operation in progress: pkg:/components/cpc/metrics/vendor/adbmobile.brs(1223)

ADBMobile Error: [media/networkService] Unable to execute GET request for URL (http://..removing the url..let me know if you need it...)
ADBMobile Error: [media/networkService] Unable to send hit, Failure Reason: Cancelled ResponseCode: -10001
```

Thanks!

**Comment by praveek** [comment]
We internally cancel and retry the request if it takes long to complete. In your case is the failure happening frequently and does the SDK recover after the error ? 

Thanks,
Praveen

**Comment by dipan-majumder** [comment]
It happens very randomly, we usually have the ADB debug disabled, after enabling there is no guarantee that it will happen, so very hard to tell if it recovers. 
But anyway, so this is an expected behavior, correct?

**Comment by praveek** [comment]
Yes. This is an expected timeout behaviour enforced in the client.
