### ISSUE TITLE
Unable to capture quality parameters from Roku for Heartbeat

### ISSUE THREAD

**Issue by patrick-mtod** [Adobe-Marketing-Cloud/media-sdks#41]
`:stream:bitrate`
`l:stream:fps`
`l:stream:dropped_frames`
`s:event:type`

**Comment by praveek** [comment]
Hi @pkhajehtoorian 

To capture quality parameters you have to notify heartbeat SDK when you have them or when they change.

Create QOS object using 
`adb_media_init_qosinfo(bitrate As Double, startupTime as Double, fps as Double, droppedFrames as Double) As Object`

and call
`ADBMobile().mediaUpdateQoS(qosinfo)`

Thanks,
Praveen

**Comment by patrick-mtod** [comment]
Hi @praveek ,
How do we get the value for qosinfo?
We can not call this function because we don't have the data. We can not get the data from Roku.
Thank you,
Patrick

**Comment by praveek** [comment]
Hi Patrick, 

We have designed the API to keep it uniform across our other platforms.
If you don't have any data, you can provide a value of `0`. I haven't looked into latest bright-script documentation but think you can get at-least bitrate and startup time from Roku. 

Thanks,
Praveen

**Comment by patrick-mtod** [comment]
Hi @praveek,
Thank you! That was helpful. How long does it take for us to see data in Adobe web interface after the Roku app launches to production?
Thanks
