### ISSUE TITLE
iOS Crashes with ADB_VHB_VideoPlayerPlugin cacheVideoInfo] 

### ISSUE THREAD

**Issue by vkspune** [Adobe-Marketing-Cloud/media-sdks#42]
We are getting crash on Crashlytics which impact more than 100 users on production. We are using  "Adobe Experience Cloud iOS Library version 4 (4.17.1 (27 Nov 2018))".
Please find below crash logs from Crashlytics and attached full logs of Crashlytics.

#8. Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x184ec4430 objc_msgSend + 16
1  CoreFoundation                 0x185b36aa8 -[__NSDictionaryM objectForKey:] + 212
2  DisneyTheater                  0x104a05570 -[ADB_VHB_VideoPlayerPlugin cacheVideoInfo] + 4301804912
3  DisneyTheater                  0x104a03020 __46-[ADB_VHB_VideoPlayerPlugin setupDataResolver]_block_invoke353 + 4301795360
4  DisneyTheater                  0x1049de280 -[ADB_HB_Callback call:] + 4301644416
5  DisneyTheater                  0x104a05260 __46-[ADB_VHB_VideoPlayerPlugin setupDataResolver]_block_invoke565 + 4301804128
6  DisneyTheater                  0x1049de280 -[ADB_HB_Callback call:] + 4301644416
7  DisneyTheater                  0x104a06080 -[ADB_VHB_VideoPlayerPlugin _pollPlayhead] + 4301807744
8  DisneyTheater                  0x104a05fd0 __47-[ADB_VHB_VideoPlayerPlugin startPlayheadTimer]_block_invoke + 4301807568
9  libdispatch.dylib              0x1855e6a14 _dispatch_client_callout + 16
10 libdispatch.dylib              0x185623640 _dispatch_continuation_pop$VARIANT$armv81 + 420
11 libdispatch.dylib              0x18562c858 _dispatch_source_invoke$VARIANT$armv81 + 528
12 libdispatch.dylib              0x1856282a4 _dispatch_root_queue_drain + 568
13 libdispatch.dylib              0x185628008 _dispatch_worker_thread3 + 112
14 libsystem_pthread.dylib        0x18588f06c _pthread_wqthread + 1268
15 libsystem_pthread.dylib        0x18588eb6c start_wqthread + 4
[videoInfo.txt](https://github.com/Adobe-Marketing-Cloud/media-sdks/files/3297812/videoInfo.txt)

[videoInfo2.txt](https://github.com/Adobe-Marketing-Cloud/media-sdks/files/3297841/videoInfo2.txt)
[videoInfo.txt](https://github.com/Adobe-Marketing-Cloud/media-sdks/files/3297842/videoInfo.txt)

**Comment by praveek** [comment]
The root cause of this crash is similar to https://github.com/Adobe-Marketing-Cloud/media-sdks/issues/43

@vkspune Can you let us know the MediaSDK version the app uses? We were recently reported a similar crash related to VideoPlayerPlugin and have been working on a fix.

Can you please reach out to [client care](https://helpx.adobe.com/contact/enterprise-support.ec.html) and open a ticket with them so that we can share you with a dev build which fixes the crash.

**Comment by vkspune** [comment]
Hi Praveek, As mentioned in the above description we are using 4.17.1 .
Hence this issue is showing up on Crashlytics and we are not able to produce in our development environment so development build won't help much So could you please provide release build where this issue has been fixed.

**Comment by vkspune** [comment]
Hi Praveek,

We are using adobeSDK not the library and its version is Adobe version: 4.17.1
Please find attached screenshot of finder and readMe file available with the package.
[ReleaseNotes.txt](https://github.com/Adobe-Marketing-Cloud/media-sdks/files/3301937/ReleaseNotes.txt)
![Screen Shot 2019-06-18 at 9 22 25 AM](https://user-images.githubusercontent.com/1772848/59692633-015fc700-91ab-11e9-9f16-280b8d7e3624.png)

**Comment by vkspune** [comment]
[ADBMediaHeartbeat version] = ios-2.2.0.354-69248a

**Comment by praveek** [comment]
@vkspune  This is the latest release which has a fix for the crash mentioned above.
https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/ios-v2.2.4

**Comment by praveek** [comment]
Hi @vkspune Any updates after testing with the new build ?

**Comment by praveek** [comment]
Reopen the issue if you see crash with new build. 
Thanks.
