### ISSUE TITLE
ADBMobile.h is missing in include folder ios-v2.2.4

### ISSUE THREAD

**Issue by vkspune** [Adobe-Marketing-Cloud/media-sdks#44]
Hi I just downloaded the latest release https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/ios-v2.2.4
But ADBMobile.h is missing in the include folder. please find attached screenshot but sample project still have it.
So could you please look into this ASAP.

![Screen Shot 2019-06-24 at 9 40 07 AM](https://user-images.githubusercontent.com/1772848/60027950-197c8e00-9664-11e9-91f4-6882c8531a18.png)

**Comment by nporter-adbe** [comment]
Hi @vkspune 👋 The `ADBMobile.h` header file is not a part of the MediaSDK, it can be found in the [Adobe Mobile Services SDK](https://github.com/Adobe-Marketing-Cloud/mobile-services).
