### ISSUE TITLE
Chromecast | Adobe | Heartbeat | Ad event calls are not in sequence

### ISSUE THREAD

**Issue by sunilvishwakarma-nbcuni** [Adobe-Marketing-Cloud/media-sdks#45]
Hi,
When we play a VOD asset and while playing when the adbreak starts below are the Hearbeat methodes I am calling:
ADBMobile.media.trackEvent('adBreakStart', info);
ADBMobile.media.trackEvent('adStarted', info);
ADBMobile.media.trackPlay();

Now, If I track the Heartbeat calls in a proxy then the **s:event: type** sequence for ads should be like - **start, aa_ad_start** and **play** but in actual these events are in a random sequence.
Please help me in fixing this issue.

Thanks,
Sunil Vishwakarma
CC: @dipanmajumder-nbcuni

**Comment by cacheung** [comment]
Hi Sunil,
     Usually the platform might send http requests out of order, but it is not an issue as we record the timestamp in each http call.

Best Regards,
Calise Cheung
Adobe Engineer

**Comment by sunilvishwakarma-nbcuni** [comment]
Hi Calise,
Below is one more scenario where I want you to confirm if it's an issue or not:

1. Cast the application to the chromecast.
2. Played a VOD asset.
3. Scrubbed from Chapter 1 to Chapter 3.
4. Scrubbed again from Chapter 3 to 2.
5. Now, a midroll ad will be played and after ad completion, a new chapter 2 will start and in this scenario, sometimes we are seeing one play call in between AdBreakComplete and Chapter_Start calls in Heartbeat.

Here is the sequence of Heartbeat methods we are calling:
ADBMobile.media.trackEvent('AdBreakComplete', info);
ADBMobile.media.trackEvent('ChapterStart', info);
ADBMobile.media.trackPlay();
 
Thanks,
Sunil Vishwakarma
CC: @dipanmajumder-nbcuni

**Comment by cacheung** [comment]
Hi Sunil,
     Can you tell me what's the timestamp/time for AdBreakComplete, Play and Chapter_Start calls when you have this case?  

Thanks,
Calise

**Comment by sunilvishwakarma-nbcuni** [comment]
Hi Calise,
Below are the request and response time details:

**AdBreakComplete**:
Request Start Time           : 3/10/19 17:1014
Request Complete Time   : 3/10/19 17:1014
Response Start Time        : 3/10/19 17:1014
Response Complete Time: 3/10/19 17:1014

**Play**:
Request Start Time          : 3/10/19 17:1014
Request Complete Time  : 3/10/19 17:1014
Response Start Time        : 3/10/19 17:1014
Response Complete Time: 3/10/19 17:1014

**Chapter_Start**:
Request Start Time          : 3/10/19 17:1014
Request Complete Time  : 3/10/19 17:1014
Response Start Time        : 3/10/19 17:1014
Response Complete Time: 3/10/19 17:1014

You see the timings in the below screenshots as well.

<img width="1354" alt="Main_Play" src="https://user-images.githubusercontent.com/55181746/67191222-e75f1b00-f40e-11e9-9c6b-f1b3f6b42b45.png">
<img width="1437" alt="Chapter_Start" src="https://user-images.githubusercontent.com/55181746/67191224-e75f1b00-f40e-11e9-84d8-49ce036aebc8.png">
<img width="1434" alt="AD_Complete" src="https://user-images.githubusercontent.com/55181746/67191235-e8904800-f40e-11e9-8dde-d1f5067493cc.png">

Thanks
Sunil Vishwakarma
CC: @dipanmajumdar-nbcuni

**Comment by cacheung** [comment]
Hi Sunil,
     Thanks for detailed info.  It shows all of three events had the same timestamp.  Since we can't guarantee the order of the http request, so it is possible sometime Play event sent right before the Chapter Start event in this case.  This is fine and should not affect the reporting.

Best Regards,
Calise Cheung
Adobe Engineer

**Comment by sunilvishwakarma-nbcuni** [comment]
Thanks, Calise!
Now, I will consider both the scenario as not an issue and if in future I will notice any mismatch sequence scenario with different timestamp I will raise a new bug.

Thanks,
Sunil Vishwakarma
