### ISSUE TITLE
Chromecast | Adobe | Heartbeat | When we scrub the playhead value getting updated before next chapter start

### ISSUE THREAD

**Issue by sunilvishwakarma-nbcuni** [Adobe-Marketing-Cloud/media-sdks#46]
Hi,
When we scrub from playhead value 10 which falls into chapter 1 to playhead value 100 which falls into chapter 4, Now the Heartbeat call just before the chapter 4 start call is having the playhead value 100 with chapter 1 info. Please let me know if it's an aspected scenario or if there is anything I need to look into to fix it.

Thanks,
Sunil Vishwakarma

**Comment by praveek** [comment]
Hi @sunilvishwakarma-nbcuni 

The SDK reports the latest playhead value passed through UpdatePlayhead API in heartbeat pings.

After seeking out of chapter 1, i would suggest calling `ChapterSkip` to end the current chapter.
The recommended order of calls 
trackEvent(ChapterStart, chapter1)
trackEvent(ChapterSkip) - After seeking out of chapter 1
UpdatePlayhead(100) 
trackEvent(ChapterStart, chapter4)

You may see the SDK sending a ping with playhead value 100 and chapter 1 info when omitting `ChapterSkip` for chapter 1 or calling UpdatePlayhead(100) before `ChapterSkip`. 

Thanks,
Praveen
