### ISSUE TITLE
ROKU | Adobe | Heartbeat | Playhead value is 0 when we resume a vod from specified position

### ISSUE THREAD

**Issue by sunilvishwakarma-nbcuni** [Adobe-Marketing-Cloud/media-sdks#47]
Hi,

When we resume a VOD from a specific position than in that scenario the Playhead value for the starting calls(trackSessionStart) in the Heartbeat is 0. We do update the Playhead value every second using the mediaUpdatePlayhead method. After trackSessionStart calls, we are getting the Playhead value equal to the specified VOD playback position.
Please let us know if the above scenario is fine or If there is a way to update the Playhead value for the starting calls when we resume a VOD from a specific position.

Thanks,
Sunil Vishwakarma
CC: @dipanmajumder-nbcuni @vimalsharma-nbcuni

**Comment by praveek** [comment]
@sunilvishwakarma-nbcuni 
The above scenario is not an issue. The main:start calls sent just after starting the session will have playhead value 0 till the tracker receives updated playhead.

Thanks,
Praveen
