### ISSUE TITLE
iOS (tvOS) crash in  [ADB_HB_TimerManager _onTick]

### ISSUE THREAD

**Issue by mirekp** [Adobe-Marketing-Cloud/media-sdks#48]
Getting some crash reports through my crash reporting tool. Using the latest MediaSDK-ios-tvos-v2.2.6 on tvOS 13.2

The stack trace:

SIGSEGV

```
Thread 9:
objc_msgSend (libobjc.A.dylib)
-[__NSFrozenDictionaryM objectForKey:] (CoreFoundation)
-[ADB_HB_TimerManager _onTick]
-[ADB_HB_TimerManager initWithService:logger:]_block_invoke
_dispatch_client_callout (libdispatch.dylib)
_dispatch_continuation_pop (libdispatch.dylib)
_dispatch_source_invoke (libdispatch.dylib)
_dispatch_root_queue_drain (libdispatch.dylib)
_dispatch_worker_thread2 (libdispatch.dylib)
_pthread_wqthread (libsystem_pthread.dylib)
start_wqthread (libsystem_pthread.dylib)
```

Any idea about this?

**Comment by praveek** [comment]
Hi @mirekp 

How frequently is this crash happening ? Do you have call-stacks of other threads during the crash ?
I would also like to know how the tracker is implemented in the app. Do you create a new tracker for each session or reuse the same tracker ? 

Thanks,
Praveen

**Comment by mirekp** [comment]
Thank you Praveen.

It is not too frequent, but it is happening time to time affecting different uses.

As for the tracker. We create a new tracker instance for playback session (which is then reused for events pertaining to that session).

As for the other threads. The only other relevant thread seems to be the main thread:

**Comment by praveek** [comment]
Thanks @mirekp for the additional information. I was able to identify the race condition which caused this crash. We are currently planning to release this fix in January after we do some additional testing.

Reach out to [client care](https://helpx.adobe.com/contact/enterprise-support.ec.html) and open a ticket if you want access to dev build which fixes the crash.

Thanks,
Praveen

**Comment by mirekp** [comment]
@praveek Great news. Thanks!

**Comment by praveek** [comment]
Hi @mirekp 
We have released [v2.2.7](https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/ios-v2.2.7) which fixes this crash. 

Thanks,
Praveen

**Comment by praveek** [comment]
@mirekp Any updates on this issue ?

**Comment by praveek** [comment]
Feel free to open this ticket if you still see this issue.
