### ISSUE TITLE
Undefined symbols when using ADBStandardMetadataKeys

### ISSUE THREAD

**Issue by igorest7** [Adobe-Marketing-Cloud/media-sdks#49]
I am getting an error when trying to use the ADBStandardMetadataKeys after installing the AdobeMediaSDK via Cocoapods.

Steps to reproduce:
1. Create a new project.
2. Add a podfile 
```
use_frameworks!

target 'AdobeMediaTest' do
  platform :tvos, '11.0'
  pod 'AdobeMediaSDK'
end
```
3. Run pod install.
4. Open workspace.
5. Import AdobeMediaSDK and try to use any of the keys. For example:
```
func testFunc() {
        _ = ADBVideoMetadataKeySHOW
    }
```
6. Try to build the project for apple tv simulator

I am seeing the following error in the build log:
```
Undefined symbols for architecture x86_64:
  "_ADBVideoMetadataKeySHOW", referenced from:
      AdobeMediaTest.ContentView.testFunc() -> () in ContentView.o
ld: symbol(s) not found for architecture x86_64
```

Interestingly Xcode does not show any error at the point of use.

I am using cocoapods version 1.8.4
Xcode 11.2.1
Sample project with the above error - https://www.dropbox.com/s/x9va9w64d488ty3/AdobeMediaTest.zip?dl=0

**Comment by praveek** [comment]
@igorest7 Thanks for the detailed report.

The standard metadata constants are defined in a separate object file in the Media SDK static library. I see that the linker is stripping these symbols when generating a framework as the object file contains only constants. 

As a quick workaround, adding -all_load or -force_load options to other_linker_flags in AdobeMediaSDK target will fix this error.

We will add a workaround and notify you once we update our pod spec. 

Thanks,
Praveen

**Comment by igorest7** [comment]
Thanks for the help @praveek, that workaround helped me.

Is there an ETA for the proper podspec fix?

**Comment by praveek** [comment]
We are planning to do a patch release for the iOS SDK early next week. I will also update the podspec with the release.

**Comment by praveek** [comment]
@igorest7 The linker error should be fixed once you `pod update` to latest version.

**Comment by igorest7** [comment]
It works fine now. Thanks for the quick turn around @praveek
