### ISSUE TITLE
Setting content channel

### ISSUE THREAD

**Issue by mimse** [Adobe-Marketing-Cloud/media-sdks#50]
Hi,

I have been digging through the documentation trying to find a way to set 

https://docs.adobe.com/content/help/en/media-analytics/using/metrics-and-metadata/audio-video-parameters.html#content-channel

I was able to set s:sp:channel by setting channel on the MediaHeartbeatConfig. 

But what we want is to track a new channel when switching content, using the same instance of heatbeat every time.

Is this possible?

Hope you can help

Using the javascript library

Thank you in advance

**Comment by praveek** [comment]
Hi @mimse 

Channel name can only be configured when creating a new tracker instance and cannot be changed later.

Thanks,
Praveen
Praveen

**Comment by mimse** [comment]
Thank you for the answer :-)
