### ISSUE TITLE
iOS (tvOS) crash in ADB_VHB_MediaHeartbeatVideoPlayerPluginDelegate getAdInfo

### ISSUE THREAD

**Issue by mirekp** [Adobe-Marketing-Cloud/media-sdks#51]
Hi. I am experiencing this crash (SIGSEGV) in my app. Reported by my crash reporting tool by multiple users on multiple OS versions. Using the latest MediaSDK-ios-tvos-v2.2.6 on tvOS 13.2.

Doesn't happen terribly often, but any thoughts would be appreciated.

Thread 10 (crashed)
```
libobjc.A.dylib | objc_retain (libobjc.A.dylib)
MyApp | -[ADB_VHB_MediaHeartbeatVideoPlayerPluginDelegate getAdInfo]
MyApp | -[ADB_VHB_VideoPlayerPlugin cacheAdInfo]
MyApp | __46-[ADB_VHB_VideoPlayerPlugin setupDataResolver]_block_invoke413
MyApp | -[ADB_HB_Callback call:]
MyApp | __46-[ADB_VHB_VideoPlayerPlugin setupDataResolver]_block_invoke565
MyApp | -[ADB_HB_Callback call:]
MyApp | -[ADB_HB_BasePlugin resolveData:]
MyApp | -[ADB_HB_PluginManager request:keys:]
MyApp | -[ADB_VHB_VideoPlayerPlugin _pollPlayhead]

```
Main thread (if relevant):

```
__ulock_wait (libsystem_kernel.dylib)
libobjc.A.dylib | objc_sync_enter (libobjc.A.dylib)
MyApp  | -[ADB_HB_PluginManager triggerEvent:]
MyApp  | -[ADB_HB_BasePlugin _trigger:info:]
MyApp  | -[ADB_VHB_VideoPlayerPlugin trackAdComplete]
MyApp  | -[ADBMediaHeartbeat _cmdAdComplete:]
MyApp  | __32-[ADBMediaHeartbeat _setupRules]_block_invoke839
MyApp  | -[ADB_HB_Callback call:]
MyApp  | -[ADBRuleEngine processRule:ruleEngineContext:]
MyApp  | -[ADBMediaHeartbeat processRule:ruleEngineContext:]
MyApp  | -[ADBMediaHeartbeat trackEvent:mediaObject:data:]
MyApp  | OmnitureAnalytics.trackEvent(_:) (OmnitureAnalytics.swift:0)

```

**Comment by praveek** [comment]
Thanks @mirekp for the report. I will take a look to see if i can reproduce this locally. 

Thanks,
Praveen

**Comment by praveek** [comment]
Hi @mirekp 
We have released [v2.2.7](https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/ios-v2.2.7) which includes stability fixes. Can you check if you still see this crash ? 

Thanks,
Praveen

**Comment by mirekp** [comment]
@praveek Thanks. Will do. It will take me a while to get the feedback as I need to put it to a build and rely on analytics (no repro steps known).

**Comment by praveek** [comment]
@mirekp Any updates on this issue ?

**Comment by praveek** [comment]
Feel free to reopen this ticket if you still see this issue.
