### ISSUE TITLE
What is aa_start for? Does the API support client generated session IDs?

### ISSUE THREAD

**Issue by gpsamson** [Adobe-Marketing-Cloud/media-sdks#55]
1. I'm comparing the JS SDK to the Media Collection API and I've noticed that the SDK has two additional start calls that point to an event type called `aa_start`. What does this event do? The Media SDK documentation is pretty vague when it comes to this event.

2. A more off-topic question - does the Media Collection API support a way to have the client generate a session ID? The documentation states that we must call the API to generate a session ID before sending heartbeat events, but this is not the case for the JS Media SDK. The JS Media SDK does not send a request to generate a session ID.

3. What is the purpose of `l:event:prev_ts`? The documentation says "The timestamp of the last event of the same type in this session." but goes on to say "The value is -1." Does a value of -1 affect the reporting in the dashboard? If this attribute is empty, will it affect reporting?

Thanks!

**Comment by praveek** [comment]
Hi @gpsamson 
1) The current JS SDK (2.x)  internally uses a different endpoint and the ping format / sequence which the SDK generates is completely different from Media Collection API. The SDK currently makes a AppMeasurement call to denote media start and `aa_start` event notifies the backend that the AppMeasurement call was successfully made from client. 

2) No. For media collection API, there must be an API call to generate session ID. 
As mentioned above current JS Media SDK is not the same as media collection API.

3) `l:event:prev_ts` is used by our backend for some metrics related calculations. The value is -1 if no previous event of same type was reported to the backend. `l:event:prev_ts` is calculated internally by the SDK and the implementation don't have to worry about the values. 

Thanks,
Praveen

**Comment by gpsamson** [comment]
Hey @praveek. Thanks for the timely response. We're trying to weigh the differences between using a client-side media SDK and using the Media Collection API. 

The biggest question we have is around the API and guaranteed ordering. Once we create a new video session and start sending events what will happen if:
1. `ping` events are not sent at exactly 1s or 10s apart? That's to say that there is some form of latency with the system sending the events to the API
2. events are sent out of order (10s of seconds apart)

**Comment by praveek** [comment]
Hey @gpsamson. Sorry for the delay.
In your scenario, are the media collection API pings directly sent from the client or is it routed through your server ?

1) How big is the latency between the ping events sent to the backend. I assume the event payload and timestamp are correctly populated from the client. 

2) How much of a reordering are we talking about here? Is it just with few of the ping events or all the events reordered ?

**Comment by gpsamson** [comment]
Hey @praveek, it's alright, thanks for responding. Yes, the events are being routed from our client to our server, then to the Media Collection API.

> 1. How big is the latency between the ping events sent to the backend. I assume the event payload and timestamp are correctly populated from the client.

Our median end-to-end latency of events sent through our servers is ~2 seconds. The event payloads will have the correct timestamps populated by the client. We are trying to understand what effect our latency will have on ping events and Media Reporting.

> How much of a reordering are we talking about here? Is it just with few of the ping events or all the events reordered?

Our server can't guarantee processing events in a first in first out (FIFO) fashion. This would impact all event ypes, not just pings. We also exponentially retry events if there is a network failure or timeout.

The Adobe documentation states "The reorder may fail if the delays between out of order calls are more than one second". What we are trying to understand is, say we have these events:

```
12:00 a
12:01 b
12:02 c
12:03 d
12:04 e
12:05 f
```

By the time they go through our system they could arrive in Adobe in this order: `b, c, a, d, e, f`.

- Will `b, c, d, e, f` be recorded and `a` rejected because the delay is greater than 1 second?
- If `a` is exponential retried, will it still be recorded by Adobe? This retry delay will only increase.
- What happens if `f` happened to be recorded first, will all previous events be lost?"

**Comment by praveek** [comment]
Currently, the backend queue size for reorder is 5 events and the events are reordered if they are sent less than a second apart. There will be an update soon which will increase the queue size to 10 and timeout to 5 seconds.  

Can you reach out to [client care](https://helpx.adobe.com/contact/enterprise-support.ec.html) and open a ticket. They can put you in touch with our backend team and you can discuss more about your server setup and how it impacts reporting. 

Thanks,
Praveen

**Comment by gpsamson** [comment]
Got it. Thank you @praveek!
