### ISSUE TITLE
Content Start without Media Start

### ISSUE THREAD

**Issue by TheFalseFriend** [Adobe-Marketing-Cloud/media-sdks#56]
Hi,

I have a situation in which an Android app is sending the expected calls to count a Media Start and a Content Start (the link call to AA, plus the HB calls 'start' and 'aa_start'). **However**, in Analytics Workspace, Media Starts are not incremented, while Content Starts are for any given stream start. 

I understand this to be theoretically impossible - is it not the case that you couldn't get a Content Start without first having had a Media Start?

The AA version is 'Android Mobile SDK v4.16.0'. The HB version is 'android-2.2.0.201-eac555'. 

Note that RSIDs, HB and AA servers are all correct in the calls. Also note there are no VISTA rules active for the suite in question. Finally note that the Adobe backend responds to all tracking calls in the usual way (ie. with a 200 OK or a 204 NO CONTENT).

Are you able to shed some light on this situation? In particular:
- Are there any situations in which Adobe would respond to a tracking call will an HTTP 200/204, but subsequently drop the call internally once ingested into the backend?
- Has there been any pertinent maintenance to internal systems recently that could affect the counting of Media Starts? 
- Has Adobe seen this issue before?
- Does the AA Mobile SDK for Android v4.16.0 suffer any known bugs, particularly race conditions?
- Are there any conceivable situations in which a Content Start would be incremented without a corresponding Media Start?

Thanks in advance.

**Comment by praveek** [comment]
@TheFalseFriend 

Media Start is computed from the analytics track call sent from the client. Content Start is computed after the heartbeat pings are processed by the heartbeat backend.  

Media Starts are counted once the analytics pings are reported to the backend for a particular session. Do you consistently see it happening for some media or does it randomly happen and the numbers seem wrong in analytics dashboard ? 

If this happens consistently in some scenario, can you please reach out to [client care](https://helpx.adobe.com/contact/enterprise-support.ec.html), open a support ticket and share us the charles dump and debug log with tracking pings. 

Thanks,
Praveen

**Comment by TheFalseFriend** [comment]
Hi @praveek, thanks for your assistance. 

This turned out to be affecting 100% of pageview calls and link calls, including the MHL analytics start call (but not any HB beats).

For anyone else stumbling upon similar such symptoms, the root cause was resolved to the 'ts' (timestamp) call parameter. The timestamp field was present in the calls, but these were getting sent to a suite that had Timestamps Enabled: false. Therefore the backend was silently dropping 100% of tracking calls (other than HB). Resolved by configuring affected app not to set timestamps.

Issue can be closed.
