### ISSUE TITLE
Offline Video Analytics Question - iOS and Android

### ISSUE THREAD

**Issue by starchey** [Adobe-Marketing-Cloud/media-sdks#59]
We support downloading videos and playing them offline in our iOS and Android apps, and we were curious what analytics we should expect to be working while offline (after network is restored)? Example, load a video, play through for a few minutes, pause, then exit. While the network is connected, we'll see our distinct trackSessionStart, trackPlay etc. events, and also a heartbeat report being sent periodically. Are we able to track all this data when offline?

Currently, our iOS app is integrated with AdobeMobileLibrary v4.17.0 and MediaSDK 2.2.0. Our Android app is integrated with AdobeMobileLibrary v4.17.1 and MediaSDK 2.2.1. We have offline analytics enabled in both ("offlineEnabled": true in ADBMobileConfig.json), but other than that, we don't have any custom code to handle analytics while offline.

In testing on iOS and Android with debug logging enabled, we've noticed "heartbeat data fails to send" logs while the video is playing. When the network is restored, we see some analytic calls go out, but reviewing the params, not certain these are accurate regarding video events (ex. seems like playhead is always 0, not sure we're getting the same start/play/pause/stop/complete events we see when connected to network, iOS sent out four requests after network restored but only one on Android).

Before debugging further, we wanted to see if offline video tracking should be working on these versions, and if so, if there is any additional code we need to add to support this? Alternatively, if not supported in these versions, would we have better luck updating to latest?

Thanks!

**Comment by praveek** [comment]
Hi @starchey 
Tracking downloaded content is not support in standalone iOS and Android Media SDK. It is supported only with latest AEP Media launch extension. 

To use this feature, you have to upgrade from AdobeMobileLibrary to the new [AEP SDK](https://aep-sdks.gitbook.io/docs/) and then follow the documentation to implement [media tracking](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-media-analytics)

Thanks,
Praveen
