### ISSUE TITLE
Memory Corruption objc_retain in [ADB_HB_ReportFilter _flushBufferReport:]

### ISSUE THREAD

**Issue by nuno-vieira** [Adobe-Marketing-Cloud/media-sdks#61]
Issue similar to https://github.com/Adobe-Marketing-Cloud/media-sdks/issues/60 but in another place. For more context, please read the issue.

Stack Trace:

Crashed: com.adobe.analytics.heartbeat.work.report (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x1ae687ca0 objc_retain + 16
1  AddonManager                   0x103c26160 -[ADB_HB_ReportFilter _flushBufferReport:] + 84
2  AddonManager                   0x103c28390 __28-[ADB_HB_ReportFilter flush]_block_invoke + 56
3  AddonManager                   0x103c3140c -[ADB_HB_Callback call:] + 76
4  AddonManager                   0x103c314d4 -[ADB_HB_Callback apply:] + 148
5  AddonManager                   0x103c30604 -[ADB_HB_Command run] + 88
6  AddonManager                   0x103c330a0 __34-[ADB_HB_CommandQueue addCommand:]_block_invoke33 + 84
7  Foundation                     0x19c0e0cc8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
8  Foundation                     0x19bfddb18 -[NSBlockOperation main] + 100
9  Foundation                     0x19c0e2f80 __NSOPERATION_IS_INVOKING_MAIN__ + 20
10 Foundation                     0x19bfdd7d4 -[NSOperation start] + 784
11 Foundation                     0x19c0e3978 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
12 Foundation                     0x19c0e3444 __NSOQSchedule_f + 180
13 libdispatch.dylib              0x19aa2c93c _dispatch_block_async_invoke2 + 104
14 libdispatch.dylib              0x19aa7d280 _dispatch_client_callout + 16
15 libdispatch.dylib              0x19aa2256c _dispatch_continuation_pop$VARIANT$mp + 412
16 libdispatch.dylib              0x19aa21cb0 _dispatch_async_redirect_invoke + 596
17 libdispatch.dylib              0x19aa2f11c _dispatch_root_queue_drain + 376
18 libdispatch.dylib              0x19aa2f8e4 _dispatch_worker_thread2 + 124
19 libsystem_pthread.dylib        0x1e06ec568 _pthread_wqthread + 212
20 libsystem_pthread.dylib        0x1e06ef874 start_wqthread + 8

**Comment by praveek** [comment]
Thanks for report @nuno-vieira. We will investigate it. How frequent is this crash ?

**Comment by nuno-vieira** [comment]
> Thanks for report @nuno-vieira. We will investigate it. How frequent is this crash ?

This one is more rare than the other one. Only affecting around 150 users and unique 150 crashes.

**Comment by praveek** [comment]
We have released [v2.2.8](https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/ios-v2.2.8) which addresses this issue. Let me know if this issue still persists.
