### ISSUE TITLE
Roku | `ifDeviceInfo.getVersion()` to be replaced by `ifDeviceInfo.getOsVersion()`

### ISSUE THREAD

**Issue by timalacey** [Adobe-Marketing-Cloud/media-sdks#64]
https://github.com/Adobe-Marketing-Cloud/media-sdks/blob/fe694b9083056d627972c572c3b35c43e7a319cf/sdks/roku/libs/adbmobile.brs#L633

`ifDeviceInfo.getVersion()` on Roku OS 10 will return `999.99E99999X`
`ifDeviceInfo.getOsVersion()` should be used

**Comment by praveek** [comment]
@timalacey We are working on fix internally. I will notify once we release an update.

**Comment by markwpearce** [comment]
@praveek Any idea on when the new version (without `getVersion`) will be available?

**Comment by praveek** [comment]
@markwpearce We are planning to release it next week. I will update this ticket once the release is live.

**Comment by addb** [comment]
@timalacey, @markwpearce 
We have released the new version of our SDK with the fix
Please get it from: https://github.com/Adobe-Marketing-Cloud/media-sdks/releases/tag/roku-v2.2.5
