### ISSUE TITLE
Missing event calls for seekStart and seekComplete subsequently

### ISSUE THREAD

**Issue by sarahs07** [Adobe-Marketing-Cloud/media-sdks#67]
Hi,

I work for SKY - NOW TV and we are firing `seekStart` and `seekComplete` events via the API below but no call is made for `seekStart` event and hence get the error below:

`17:43:51 GMT+0100 (GMT+01:00).066] [ERROR] [RuleEngine] API:trackEvent(SeekComplete) -  MediaHeartbeat is not tracking seek events, call "API:trackEvent(SeekStart)" before "API:trackEvent(SeekComplete)".`

this.mediaHeartbeat.trackEvent('seekStart');
this.mediaHeartbeat.trackEvent('seekComplete');

Using lib v 2.2.0 - 2019-02-12

Has there been a similar bug that's resolved in later version? 

Thanking you in anticipation.

**Comment by praveek** [comment]
@sarahs07 
Just to clarify is this regarding the JS SDK? I am not aware of any bug around seekStart and seekComplete events. Can you share me debug logs or test page so that i can look into the issue?

**Comment by cacheung** [comment]
Closing this ticket due to low activity.  Please open a new one if you still encountering the issue.
