### ISSUE TITLE
Roku - no way to pass config other than through a file

### ISSUE THREAD

**Issue by ahwayakchih** [Adobe-Marketing-Cloud/media-sdks#69]
Hi,

In the project i'm working on, there are some config variables that are not known at the build time.
I found in `adbmobile.brs` code that it tries to load the config file from `tmp:/` first, and then from `pkg:/` if the first one is not found.
So, for now, i'm loading base JSON config file, parsing it, overriding specific values, formatting back to JSON and then writing to `tmp:/`, before initializing the library. It works, but it's not what i would call an optimal solution :D.

Is there a plan to allow for passing a config object to the init function instead of insisting on loading config from a hardcoded path?
I could create a patch and PR, but i'm not sure if you accept contributions.
Thanks,
Regards

**Comment by addb** [comment]
Hi @ahwayakchih,

The idea is to have the config file in source directory so the users don't have to pass in the path. Is it possible for you to keep the config file in project source directory(Refer our sample app: https://github.com/Adobe-Marketing-Cloud/media-sdks/tree/master/sdks/roku/samples/SampleSceneGraphPlayer)? 

The option to pass in custom path or passing to a function is not in our roadmap currently. I will discuss this request with the team.

Thanks,
Arjun Bhadra

**Comment by ahwayakchih** [comment]
Hi @addb,

Thanks for the answer!

We need to override some of the values (`analytics.rsids` for example) after the build, e.g., app is launched, we download some additional config from server, and then init everything else.
Also i don't like adding random files in project's root directory. We have subdirectory for various config files :).

So passing custom path alone would not help here, best would be to pass the config object to the init function.
Anyway, i understand it's not a common request (although i think that passing config object to init function is quite common for many libraries i used before), so the workaround will have to do for now.

Thanks,
Regards,
