### ISSUE TITLE
Roku - Equivalent of Media.createStateObject

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/media-sdks#71]
We are looking to create a custom state in VideoPlayer, but we are not able to find the proper method for it in Roku SDK.

We would like to achieve something like this,
```javascript
// StateStart (ex: Mute is switched on)
  var stateObject = ADB.Media.createStateObject(ADB.Media.PlayerState.Mute);
  tracker.trackEvent(ADB.Media.Event.StateStart, stateObject);

// StateEnd (ex: Mute is switched off)
  tracker.trackEvent(ADB.Media.Event.StateEnd, stateObject); 
```

This snippet is from JavaScript reference documentation.
https://adobe-marketing-cloud.github.io/media-sdks/reference/javascript_3x/APIReference.html

**Comment by nishantkp** [comment]
Hi @cacheung,

is there any alternative way to achieve results like state or do you have an ETA on when this feature will be available?

**Comment by cacheung** [comment]
Hi @nishantkp 
     Currently player state tracking is not supported in the Roku SDK, we don't have an ETA for this yet.  One way to have support for player state tracking is to implement the Media Collection API instead (bypass the SDK).  
     Reference doc: https://experienceleague.adobe.com/docs/media-analytics/using/media-collection-api/mc-api-overview.html
     
Thanks,
Calise

**Comment by cacheung** [comment]
Hi @nishantkp 
     Yes,  you will need to handle all the media events by your own implementation with Media Collection  API.

Thanks,
Calise

**Comment by cacheung** [comment]
@nishantkp and if we have any update for adding player state tracking to Roku, will let you know.
