### ISSUE TITLE
Media-sdks migration issue

### ISSUE THREAD

**Issue by nasibaliansari** [Adobe-Marketing-Cloud/media-sdks#75]
Hi Team,

While migration I unable to found substitute of below - 
`ADBMediaHeartbeatDelegate`
`ADBMediaHeartbeatConfig`
`ADBMediaObjectKeyStandardMediaMetadata`

in new SDK
`pod 'AEPMedia'`

I am using below method of delegate `ADBMediaHeartbeatDelegate` -
`getQoSObject()`
`getCurrentPlaybackTime()`

I was trying to create a ticket on migration support but unable to do that. Please let me know if you need additional info.

**Comment by emdobrin** [comment]
Hi @nasibaliansari, wanted to check how is the migration going and if the response above answered your question?

**Comment by emdobrin** [comment]
Closing, question answered above.
