### ISSUE TITLE
[ROKU] Override a.media.channel

### ISSUE THREAD

**Issue by dyue** [Adobe-Marketing-Cloud/media-sdks#81]
Currently, the channel is always from ADBMobileConfig.json:
```
            contextData["a.media.channel"] = _adb_config().mChannel
```

Would be nice if it's overridable from mediaInfo:
```
            mediaChannel = mediaInfo["channel"]
            if mediaChannel = invalid then mediaChannel = _adb_config().mChannel 
            contextData["a.media.channel"] = mediaChannel
```

**Comment by addb** [comment]
Hi @dyue,

Thanks for the feedback. We do have a newer version of the Roku SDK [AEP Roku SDK](https://github.com/adobe/aepsdk-roku) which supports our Adobe Edge Network workflow i.e sending data to the Adobe Experience Platform. It supports updating configuration. We are also putting all our resources in adding features to the newer AEP Roku SDK. Please give it a try and let us know if you any questions concerns. 

Documentation: https://github.com/adobe/aepsdk-roku/tree/main/Documentation
