### ISSUE TITLE
Request: Include Version # in lib code

### ISSUE THREAD

**Issue by addison-adler** [Adobe-Marketing-Cloud/media-sdks#84]
It is difficult to identify SDK versions from the vendor SDK/code once it is integrated into a project. Please include the version # in the adbmobile.brs, adbmobiletask.xml, and adbmobiletask.brs files

**Comment by addb** [comment]
@addison-adler, We do have version number in `adbmobile.brs`. You should use `getVersion()` API to get the SDK version.

**Comment by addison-adler** [comment]
Ah, I see. That's not the most obvious when just looking at the code to
check if we need to upgrade, since thats deeper within the diff, but I
appreciate you pointing out where to find it 👍
